### ISSUE TITLE
Would be nice to have heatmaps and parallel analysis in the same bayeslite session on Ubuntu 14.04

### ISSUE THREAD

**Issue by axch** [probcomp/bayeslite#121]
Here is what I tried:

```
cd examples/satellites;
(echo ".hook ../../bdbcontrib/contrib_util.py" && \
 echo ".hook ../../bdbcontrib/contrib_plot.py" && \
 echo ".hook ../../bdbcontrib/contrib_math.py" && \
 echo ".readtohtml satellites.bql ../build/satellites/") \
| PYTHONPATH=../../:$$PYTHONPATH bayeslite -m
```

At first it fails with

```
Welcome to the Bayeslite 0.1.dev20150727-234-g630833d shell.
Type `.help' for help.
bayeslite> Loading hooks at ../../bdbcontrib/contrib_util.py...
added command ".readtohtml"
<snip>
Performing INITIALIZE 16 MODELS FOR satellites_cc;
Performing ANALYZE satellites_cc FOR 4 MINUTES CHECKPOINT 2 ITERATION WAIT;
Exception RuntimeError: RuntimeError('main thread is not in main loop',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0x2afd8e6c1b48>> ignored
Tcl_AsyncDelete: async handler deleted by the wrong thread
bayeslite> Aborted (core dumped)
```

Assuming this was Tcl's fault, I tried setting my Matplotlib backend to GtkAgg.  Then this happened:

```
Welcome to the Bayeslite 0.1.dev20150727-234-g630833d shell.
Type `.help' for help.
bayeslite> Loading hooks at ../../bdbcontrib/contrib_util.py...
added command ".readtohtml"
<snip>
Performing .show 'INFER dry_mass_kg AS "Inferred Dry Mass (confidence 0.6)", launch_mass_kg AS "Inferred Launch Mass (confidence 0.6)" WITH CONFIDENCE 0.6 FROM satellites_cc WHERE class_of_orbit = GEO;' -m --filename ../build/satellites/fig_4.png
Performing .heatmap 'ESTIMATE PAIRWISE CORRELATION FROM satellites_cc;' --filename ../build/satellites/fig_5.png
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/bayeslite/shell/hook.py", line 57, in __call__
    return self.func(*args)
  File "../../bdbcontrib/contrib_plot.py", line 143, in zmatrix
    row_ordering=row_ordering, col_ordering=col_ordering)
  File "/home/axch/work/pcp/bdbcontrib/bdbcontrib/plotutils.py", line 412, in zmatrix
    cm = sns.clustermap(data_df, **clustermap_kws)
  File "/usr/local/lib/python2.7/dist-packages/seaborn/matrix.py", line 895, in clustermap
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/seaborn/matrix.py", line 813, in plot
    self.plot_matrix(colorbar_kws, mask, **kws)
  File "/usr/local/lib/python2.7/dist-packages/seaborn/matrix.py", line 803, in plot_matrix
    cbar_kws=colorbar_kws, mask=mask, **kws)
  File "/usr/local/lib/python2.7/dist-packages/seaborn/matrix.py", line 292, in heatmap
    plotter.plot(ax, cbar_ax, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/seaborn/matrix.py", line 177, in plot
    if axis_ticklabels_overlap(xtl):
  File "/usr/local/lib/python2.7/dist-packages/seaborn/utils.py", line 374, in axis_ticklabels_overlap
    bboxes = [l.get_window_extent() for l in labels]
  File "/usr/lib/pymodules/python2.7/matplotlib/text.py", line 752, in get_window_extent
    raise RuntimeError('Cannot get window extent w/o renderer')
RuntimeError: Cannot get window extent w/o renderer
bayeslite> Cannot get window extent w/o renderer
Performing ESTIMATE COLUMNS DEPENDENCE PROBABILITY WITH perigee_km AS "Probability of Dependence with Perigee" FROM satellites_cc ORDER BY "Probability of Dependence with Perigee" DESC LIMIT 10;
Performing ESTIMATE COLUMNS DEPENDENCE PROBABILITY WITH longitude_radians_of_geo AS "Probability of Dependence with Longitude Radians" FROM satellites_cc ORDER BY "Probability of Dependence with Longitude Radians" DESC LIMIT 10;
Performing .heatmap 'ESTIMATE PAIRWISE DEPENDENCE PROBABILITY FROM satellites_cc;' --filename ../build/satellites/fig_6.png
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/bayeslite/shell/hook.py", line 57, in __call__
    return self.func(*args)
  File "../../bdbcontrib/contrib_plot.py", line 143, in zmatrix
    row_ordering=row_ordering, col_ordering=col_ordering)
  File "/home/axch/work/pcp/bdbcontrib/bdbcontrib/plotutils.py", line 412, in zmatrix
    cm = sns.clustermap(data_df, **clustermap_kws)
  File "/usr/local/lib/python2.7/dist-packages/seaborn/matrix.py", line 895, in clustermap
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/seaborn/matrix.py", line 813, in plot
    self.plot_matrix(colorbar_kws, mask, **kws)
  File "/usr/local/lib/python2.7/dist-packages/seaborn/matrix.py", line 803, in plot_matrix
    cbar_kws=colorbar_kws, mask=mask, **kws)
  File "/usr/local/lib/python2.7/dist-packages/seaborn/matrix.py", line 292, in heatmap
    plotter.plot(ax, cbar_ax, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/seaborn/matrix.py", line 177, in plot
    if axis_ticklabels_overlap(xtl):
  File "/usr/local/lib/python2.7/dist-packages/seaborn/utils.py", line 374, in axis_ticklabels_overlap
    bboxes = [l.get_window_extent() for l in labels]
  File "/usr/lib/pymodules/python2.7/matplotlib/text.py", line 752, in get_window_extent
    raise RuntimeError('Cannot get window extent w/o renderer')
RuntimeError: Cannot get window extent w/o renderer
Cannot get window extent w/o renderer
Performing ESTIMATE COLUMNS DEPENDENCE PROBABILITY WITH anticipated_lifetime AS  "Probability of Dependence with Lifetime" FROM satellites_cc ORDER BY "Probability of Dependence with Lifetime" DESC LIMIT 10;
<snip>
```

Trying the other plausible-looking backends didn't help.  Any help?

**Comment by gregory-marton** [comment]
Instance of #105 and so a duplicate now?

**Comment by riastradh-probcomp** [comment]
No.  Different failure:

      File "/usr/lib/pymodules/python2.7/matplotlib/text.py", line 752, in get_window_extent
        raise RuntimeError('Cannot get window extent w/o renderer')
    RuntimeError: Cannot get window extent w/o renderer
    Cannot get window extent w/o renderer

**Comment by riastradh-probcomp** [comment]
It's not clear to me that this is related to the shell either.
