### ISSUE TITLE
Analyze crashes when checkpointing is enabled

### ISSUE THREAD

**Issue by marcoct** [probcomp/bayeslite#254]
```
Traceback (most recent call last):
  File "join_and_analyze.py", line 66, in <module>
    bdb.execute('ANALYZE cyto_cc FOR 120 MINUTES CHECKPOINT 60 SECONDS WAIT')
  File "build/bdist.linux-x86_64/egg/bayeslite/bayesdb.py", line 158, in execute
  File "build/bdist.linux-x86_64/egg/bayeslite/bql.py", line 458, in execute_phrase
  File "build/bdist.linux-x86_64/egg/bayeslite/metamodels/crosscat.py", line 1008, in analyze_models
UnboundLocalError: local variable 'diagnostics' referenced before assignment
```
Removing checkpointing removes the crash. Of possible relevance is that without checkpointing, analyze is often bound with 1 cpu utilized even though 60 cpus were allocated and 32 models were being run. This was produced on the head of bayeslite master branch as of yesterday (299ae5078). The table contains 6400 rows, and 1112 columns, of which ~800 are reals, and ~300 are booleans.

This may be reproducible with this bdb file (on probcomp1), which contains the same data, but for which I already ran analyze succesfully for 120 minutes with the checkpointing turned off:
```
/scratch/marcoct/cyto/cyto11.bdb
```
and these commands:
```
import bayeslite
from bayeslite.sqlite3_util import sqlite3_quote_name as quote

seed = 0
import os
os.environ['BAYESDB_WIZARD_MODE'] = '1'
import crosscat
import crosscat.MultiprocessingEngine as ccme
import bayeslite.metamodels.crosscat
cc = ccme.MultiprocessingEngine(seed=seed, cpu_count=60)
ccmm = bayeslite.metamodels.crosscat.CrosscatMetamodel(cc)
bdb = bayeslite.bayesdb_open(pathname="/scratch/marcoct/cyto/cyto11.bdb", builtin_metamodels=False)
bayeslite.bayesdb_register_metamodel(bdb, ccmm)
bdb.execute('ANALYZE cyto_cc FOR 120 MINUTES CHECKPOINT 60 SECONDS WAIT')
```
For reference, this error was originally produced on this script:
```
(venv)marcoct@probcomp-1:~/dev/art/ppl/bayesdb/cyto/annotations$ python join_and_analyze.py
```

**Comment by riastradh-probcomp** [comment]
Fixed in b0c29f8e0d9ea05134d0fbdfb706096e588e5bd7.
