### ISSUE TITLE
Opening two bdb instances causes 'database is locked'

### ISSUE THREAD

**Issue by fsaad** [probcomp/bayeslite#285]
In one shell session

```
bayeslite> ANALYZE solvers FOR 30 ITERATION WAIT;
Traceback (most recent call last):
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/shell/core.py", line 133, in default
    cursor = bql.execute_phrase(self._bdb, phrase)
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/bql.py", line 459, in execute_phrase
    ckpt_seconds=phrase.ckpt_seconds)
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/metamodels/crosscat.py", line 1038, in analyze_models
    'iterations': iterations_in_ckpt,
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/bayesdb.py", line 236, in sql_execute
    self.sql_tracer, self._do_sql_execute, string, bindings)
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/bayesdb.py", line 178, in _maybe_trace
    return meth(string, bindings)
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/bayesdb.py", line 239, in _do_sql_execute
    return bql.BayesDBCursor(self, self.sqlite3.execute(string, bindings))
OperationalError: database is locked
```

In the other shell session

```
bayeslite> CREATE TABLE solvers_corr AS ESTIMATE CORRELATION FROM PAIRWISE COLUMNS OF solvers_cc;
Traceback (most recent call last):
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/shell/core.py", line 133, in default
    cursor = bql.execute_phrase(self._bdb, phrase)
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/bql.py", line 85, in execute_phrase
    bdb.sql_execute(out.getvalue(), out.getbindings())
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/bayesdb.py", line 249, in savepoint
    yield
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/txn.py", line 40, in bayesdb_savepoint
    yield
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/fsaad/pcp/bayeslite/build/lib.linux-x86_64-2.7/bayeslite/sqlite3_util.py", line 61, in sqlite3_savepoint
    db.execute("RELEASE x%s" % (savepoint,))
OperationalError: database is locked
```

**Comment by riastradh-probcomp** [comment]
Only if you're trying to write to it simultaneously, and in that case we probably ought to ask sqlite3 to block rather than fail.

**Comment by fsaad** [comment]
Right -- both `CREATE TABLE` and `ANALYZE` are writing, although I did not explicitly `checkpoint`.

**Comment by gregory-marton** [comment]
Given #92, could we easily open one just for reading?

**Comment by gregory-marton** [comment]
Sounds like a feature, or at least not a bug, if both are trying to write.

**Comment by riastradh-probcomp** [comment]
The salient point is we may want to ask sqlite3 to block rather than fail in certain cases.

**Comment by fsaad** [comment]
Duplicate of https://github.com/probcomp/bayeslite/issues/378
