### ISSUE TITLE
TypeError: initialize() takes at least 5 arguments (7 given)

### ISSUE THREAD

**Issue by leocasarsa** [probcomp/bayeslite#400]
```
$python analyze_beta.py 
/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
:0: FutureWarning: IPython widgets are experimental and may change in the future.
Traceback (most recent call last):
  File "analyze_beta.py", line 35, in <module>
    bdb.execute('''INITIALIZE 32 MODELS IF NOT EXISTS FOR gusto_beta_cc''')
  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 215, in execute
    self.tracer, self._do_execute, string, bindings)
  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 223, in _maybe_trace
    return meth(string, bindings)
  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 264, in _do_execute
    cursor = bql.execute_phrase(self, phrase, bindings)
  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/bql.py", line 438, in execute_phrase
    model_config)
  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/metamodels/crosscat.py", line 803, in initialize_models
    row_initialization=model_config['row_initialization'],
TypeError: initialize() takes at least 5 arguments (7 given)
```

**Comment by leocasarsa** [comment]
analyze_beta.py:

```
import crosscat
import crosscat.MultiprocessingEngine as ccme

import os
os.environ['BAYESDB_WIZARD_MODE'] = '1'
import bayeslite

import bayeslite.metamodels.crosscat
from bayeslite.metamodels.crosscat import CrosscatMetamodel
import bayeslite
from bayeslite.read_pandas import bayesdb_read_pandas_df

import bdbcontrib
from bdbcontrib import cursor_to_df as df
from bdbcontrib.recipes import quickstart

import pandas as pd

bdb_path = './bdb/gusto_beta.bdb'
csv_path = './data/preprocessed_gusto_beta.csv'
with bayeslite.bayesdb_open(bdb_path, builtin_metamodels=False) as bdb:
    crosscat = ccme.MultiprocessingEngine(seed=1)
    metamodel = CrosscatMetamodel(crosscat)
    bayeslite.bayesdb_register_metamodel(bdb, metamodel)


    gusto_beta = pd.read_csv(csv_path)
    bayesdb_read_pandas_df(bdb, 'gusto_beta', gusto_beta, create=True)

    bdb.execute('''
        CREATE GENERATOR gusto_beta_cc IF NOT EXISTS
        FOR gusto_beta USING crosscat(GUESS(*))
    ''')
    bdb.execute('''INITIALIZE 32 MODELS IF NOT EXISTS FOR gusto_beta_cc''')
    bdb.execute('''ANALYZE gusto_beta_cc FOR 500 ITERATIONS WAIT;''')
```

**Comment by leocasarsa** [comment]
Same thing happens when using quickstart:

New analyze_beta.py
```
with bayeslite.bayesdb_open(bdb_path, builtin_metamodels=False) as bdb:
    crosscat = ccme.MultiprocessingEngine(seed=1)
    metamodel = CrosscatMetamodel(crosscat)
    bayeslite.bayesdb_register_metamodel(bdb, metamodel)


    # gusto_beta = pd.read_csv(csv_path)  
    # bayesdb_read_pandas_df(bdb, 'gusto_beta', gusto_beta, create=True)

    # bdb.execute('''
    #     CREATE GENERATOR gusto_beta_cc IF NOT EXISTS
    #     FOR gusto_beta USING crosscat(GUESS(*))
    # ''')
    # bdb.execute('''INITIALIZE 32 MODELS IF NOT EXISTS FOR gusto_beta_cc''')
    # bdb.execute('''ANALYZE gusto_beta_cc FOR 500 ITERATIONS WAIT;''')


    gusto_beta = quickstart(name='gusto_beta', csv_path=csv_path, bdb_path=bdb_path)
    q = gusto_beta.q

    gusto_beta.analyze(models=1, iterations=1)
    gusto_beta.analysis_status()
```

```
$ python analyze_beta.py 
/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
:0: FutureWarning: IPython widgets are experimental and may change in the future.
BQL [SELECT COUNT(*) FROM "gusto_beta"] [()]
BQL [
        CREATE GENERATOR "gusto_beta_cc" IF NOT EXISTS FOR "gusto_beta" USING crosscat( GUESS(*) )] [()]
BQL [INITIALIZE 1 MODELS IF NOT EXISTS FOR gusto_beta_cc] [()]
ERROR: 
Traceback (most recent call last):

  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bdbcontrib/recipes.py", line 149, in query
    res = self.bdb.execute(query_string, bindings)

  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 215, in execute
    self.tracer, self._do_execute, string, bindings)

  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 223, in _maybe_trace
    return meth(string, bindings)

  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 264, in _do_execute
    cursor = bql.execute_phrase(self, phrase, bindings)

  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/bql.py", line 438, in execute_phrase
    model_config)

  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/metamodels/crosscat.py", line 803, in initialize_models
    row_initialization=model_config['row_initialization'],

TypeError: initialize() takes at least 5 arguments (7 given)

BQL [ANALYZE gusto_beta_cc FOR 1 ITERATIONS CHECKPOINT 1 ITERATION WAIT] [()]
ERROR: 
Traceback (most recent call last):

  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bdbcontrib/recipes.py", line 149, in query
    res = self.bdb.execute(query_string, bindings)

  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 215, in execute
    self.tracer, self._do_execute, string, bindings)

  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 223, in _maybe_trace
    return meth(string, bindings)

  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 264, in _do_execute
    cursor = bql.execute_phrase(self, phrase, bindings)

  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/bql.py", line 466, in execute_phrase
    ckpt_seconds=phrase.ckpt_seconds)

  File "/scratch/home/casarsa/venv/20160504-latestbdb/local/lib/python2.7/site-packages/bayeslite/metamodels/crosscat.py", line 936, in analyze_models
    (core.bayesdb_generator_name(bdb, generator_id),))

BQLError: No models to analyze for generator: gusto_beta_cc

BQL [SELECT iterations FROM bayesdb_generator_model
                           WHERE generator_id = (
                            SELECT id FROM bayesdb_generator WHERE name = ?)] [('gusto_beta_cc',)]
BQL [SELECT iterations FROM bayesdb_generator_model
                           WHERE generator_id = (
                            SELECT id FROM bayesdb_generator WHERE name = ?)] [('gusto_beta_cc',)]
```

**Comment by fsaad** [comment]
update crosscat and bayeslite

**Comment by leocasarsa** [comment]
They are already the latest version, according to ```packaging/build-bayeslite-venv.sh```
```
>>> bdbcontrib.__version__
'0.1.7'
>>> bayeslite.__version__
'0.1.6'
>>> crosscat.__version__
'0.1.54'
```

**Comment by leocasarsa** [comment]
To reproduce this problem, ssh probcomp-2 and,
```
. /scratch/home/casarsa/venv/20160504-latestbdb/bin/activate/
python /scratch/home/casarsa/Shara/gusto/beta_belhal/analyze_beta.py
```
