### ISSUE TITLE
Failed to make or run tests

### ISSUE THREAD

**Issue by kk00ss** [probcomp/bayeslite#424]
I'm not familiar with python, but I guess simple make should work fine.
```bash
kos@kos-VirtualBox:~/Downloads/bayeslite-master$ make
python  setup.py  build
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    pkg_version, full_version = get_version()
  File "setup.py", line 51, in get_version
    'git', 'describe', '--dirty', '--long', '--match', tag,
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Makefile:31: recipe for target 'build' failed
make: *** [build] Error 1

```

**Comment by kk00ss** [comment]
Doesn't matter, I'm loading docker image.
